# This file specifies the metadata of this Hugo theme

name = "Hugo-plus"
author = "Daniel Hatch (h4tch)"
homepage = "http://h4tch.github.com/project/hugo-plus"
description = "Fully functional and customizable static website platform."
source_repo = "http://www.github.com/h4tch/hugo-plus"
license = "MIT"
licenselink = "LICENSE.md"

tags = ["blog",""]
features = ["blog","project","authors","series","streams","themes","layouts","components","plugins"]

[author]
	name = "Daniel Hatch"
	homepage = "http://h4tch.github.com"

[original]
	author =  "Daniel Hatch"
	homepage = "http://h4tch.github.com"
	repo = "http://github.com/h4tch/hugo-plus"


