
author = "Daniel Hatch (h4tch)"
name = "Hugo-plus"
homepage = "http://h4tch.github.com/project/hugo-plus"
description = "Modular feature-full website built with Bootstrap"
source_repo = "http://www.github.com/h4tch/hugo-plus"
license = "MIT"
licenselink = "LICENSE"

tags = ["blog",""]
features = ["blog","project","authors","series","pages"]

[author]
	name = "Daniel Hatch"
	homepage = "http://h4tch.github.com"

[original]
	author =  "Daniel Hatch"
	homepage = "http://h4tch.github.com"
	repo = "http://github.com/h4tch/hugo-plus"


